---
# Setup docker environment for testing

- hosts: all
  become: true
  tasks:

  # install docker

  - name: install docker
    apt:
      name:
        - docker.io
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]
    
  # create docker directory structure

  # copy docker compose file over

  # start container