---
# Setup docker environment for testing

- name: install docker
  apt:
    name:
      - docker.io
    state: latest
    update_cache: yes
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Install docker-compose software
  apt:
    name:
    - docker-compose
    state: present
  notify:
    - restart docker
    
- name: Create docker directory structure
  become: yes
  file:
    path: /home/rick/docker/share
    owner: rick
    group: docker
    mode: 0775
    state: directory
  tags: docker

- name: Create homeassistant directory structure
  become: yes
  file:
    path: /home/rick/docker/homeassist
    owner: rick
    group: docker
    mode: 0775
    state: directory

- name: Add rick user to docker group
  user:
    name: rick
    groups: docker
    append: yes
    state: present

- name: Add simone user to docker group
  user:
    name: simone
    groups: docker
    append: yes
    state: present

- name: copy docker-compose.yml file
  copy:
    src: docker-compose.yml
    dest: /home/rick/docker/docker-compose.yml
    owner: rick
    group: rick
    mode: 0644

- name: copy hsLogs.sh file
  copy:
    src: hsLogs.sh
    dest: /home/rick/docker/hsLogs.sh
    owner: rick
    group: rick
    mode: 0744

- name: copy home.tar.gz file
  copy:
    src: /home/rick/home.tar.gz
    dest: /home/rick/docker/homeassist
    owner: rick
    group: rick
    mode: 0644

- name: check if config directory exits for extract task
  stat:
    path: /home/rick/docker/homeassist/config
  register: file_details

- name: Extract home.tar.gz into /home/rick/docker/homeassist
  unarchive:
    src: /home/rick/docker/homeassist/home.tar.gz
    dest: /home/rick/docker/homeassist
    remote_src: yes
  when: file_details.stat.exists == False

- name: run the docker-compose to start containers
  community.general.docker_compose:
    project_src: /home/rick/docker/
  register: output

- ansible.builtin.debug:
    var: output
  
...