version: "3"
services:
  homeassistant:
    container_name: home-assistant
#    image: homeassistant/home-assistant:0.104.3
    image: homeassistant/home-assistant:stable
    volumes:
      - '/home/rick/docker/homeassist/config:/config'
    environment:
      - TZ=America/New_York
    restart: always
    network_mode: host
